apiVersion: v1
kind: Service
metadata:
  name: mlm-srv
  namespace: production

spec:
  selector:
    app: mlm-test
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
