apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlm-test-app
  namespace: production
spec:
  replicas: {{ .Values.image.replicas }}
  selector:
    matchLabels:
      app: mlm-test

  template:
    metadata:
      labels:
        app: mlm-test
    
     
    spec:
      containers:
      - name: mlm-test
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
  
