name: Deploy InfraStructure

on:
  repository_dispatch:
    types: ["dispatch_tf"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

    steps:
      - name: checkout TF and helm files to runner
        uses: actions/checkout@v4
      - run: |
          chmod +x ./start.sh
          ./start.sh    
          echo "${{ github.event.client_payload.service }}"
          echo "${{ github.event.client_payload.revision }}"
          echo "running terraform"

      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"
      
      - name: boostrap s3 for state
        run: terraform -chdir=bootstrap_s3 init

      - name: setup s3 as state bucket
        run: terraform -chdir=bootstrap_s3 apply -auto-approve

      - name: Terraform Init
        run: terraform -migrate-state init
        

      # apply the new image tag from CI
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ github.event.client_payload.revision }}"

