name: Deploy InfraStructure

on:
  repository_dispatch:
    types: ["dispatch_tf"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x ./start.sh
          ./start.sh    
          echo ${{ github.event.client_payload.service }}
          echo ${{ github.event.client_payload.revision }}