name: Deploy InfraStructure

on:
  repository_dispatch:
    types: ["dispatch_tf"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - run: |
          chmod +ox ./start.sh
          ./start.sh    
          echo ${{ github.event.inputs.service }}
          echo ${{ github.event.inputs.revision }}